config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/tables')

  resource :session, only: [:new, :create, :destroy]
  get '/tables', to: 'tables#index'

  resources :actions, path: '/tables/actions' do
    get :autocomplete_action_title, :on => :collection
    get :autocomplete_action_code, :on => :collection
  end

  resources :types, path: '/tables/types' do
    get :autocomplete_type_title, :on => :collection
  end

  resources :themes, path: '/tables/themes' do
    get :autocomplete_theme_title, :on => :collection
    get :autocomplete_theme_code, :on => :collection
  end

  resources :costs, path: '/tables/costs' do
    get :autocomplete_cost_title, :on => :collection
    get :autocomplete_cost_unit, :on => :collection
  end

  resources :species, path: '/tables/species' do
    get :autocomplete_species_common_name, :on => :collection
    get :autocomplete_species_latin_name, :on => :collection
  end

  resources :tasks, path: '/tables/tasks' do
    get :autocomplete_task_title, :on => :collection
    get :autocomplete_task_code, :on => :collection
  end

  resources :constraints, path: '/tables/constraints' do
    get :autocomplete_constraint_title, :on => :collection
  end

  resources :links, path: '/tables/links' do
    get :autocomplete_link_link, :on => :collection
  end

  resources :categories, path: '/tables/categories' do
    get :autocomplete_category_title, :on => :collection
  end

  resources :units, path: '/tables/units' do
    get :autocomplete_unit_abbreviation, :on => :collection
    get :autocomplete_unit_name, :on => :collection
  end

  resources :periods, path: '/tables/periods'
  resources :actions_actions, path: '/tables/actionsActions'
  resources :tasks_tasks, path: '/tables/tasksTasks'
  resources :species_actions, path: '/tables/speciesActions'

  # Default route (if unknown url)
  match '*path' => redirect('/tables'), via: [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/constraint.rb
class Constraint < ApplicationRecord
  belongs_to :task, optional: true

  before_validation :strip_blanks

  validates_presence_of :title, :message => 'Le titre de la contrainte doit être spécifié.'
  validates_length_of :title, :maximum => 40, :message => 'Le titre de la contrainte doit avoir maximum 40 caractères.'
  validates_numericality_of :task_id, :greater_than_or_equal_to => 0, :message => 'Choisir une tâche pour cette contrainte.'

  # Function to remove spaces in the field
  def strip_blanks
    self.title = self.title.strip
  end

  # Function search to search a keyword through a form
  def self.search(keyword, task)

    if task != "Indifférent"
      sql_task = "task_id = #{task.to_f}"
    else
      sql_task = ""
    end

    if keyword && sql_task == ""
      where("title iLIKE :term OR description iLIKE :term", term: "%#{keyword}%").order(updated_at: :desc)
      # iLIKE -> case insensitive
    elsif keyword && sql_task != ""
      where(sql_task + " AND (title iLIKE :term OR description iLIKE :term)", term: "%#{keyword}%").order(updated_at: :desc)
    else
      all.order(updated_at: :desc)
    end
  end
end

app/controllers/constraints_controller.rb
class ConstraintsController < AuthenticateController
  before_action :set_constraint, only: [:show, :edit, :update, :destroy]
  autocomplete :constraint, :title, :full => true

  # GET /constraints
  # GET /constraints.json
  def index
    keyword = params[:keyword]
    task = params[:task_id]
    @constraints = Constraint.search(keyword, task)
  end

  # GET /constraints/1
  # GET /constraints/1.json
  def show
  end

  # GET /constraints/new
  def new
    @constraint = Constraint.new
  end

  # GET /constraints/1/edit
  def edit
  end

  # POST /constraints
  # POST /constraints.json
  def create
    @constraint = Constraint.new(constraint_params)

    respond_to do |format|
      if @constraint.save
        format.html { redirect_to @constraint, notice: 'La contrainte a été créée.' }
        format.json { render :show, status: :created, location: @constraint }
      else
        format.html { render :new }
        format.json { render json: @constraint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /constraints/1
  # PATCH/PUT /constraints/1.json
  def update
    respond_to do |format|
      if @constraint.update(constraint_params)
        format.html { redirect_to @constraint, notice: 'La contrainte a été mise à jour.' }
        format.json { render :show, status: :ok, location: @constraint }
      else
        format.html { render :edit }
        format.json { render json: @constraint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /constraints/1
  # DELETE /constraints/1.json
  def destroy
    @constraint.destroy
    respond_to do |format|
      format.html { redirect_to constraints_url, notice: 'La contrainte a été supprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_constraint
      @constraint = Constraint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def constraint_params
      params.require(:constraint).permit(:title, :description, :task_id)
    end
end

app/helpers/constraints_helper.rb
module ConstraintsHelper
end

app/views/constraints/_form.html.erb
<%= form_with(model: constraint, local: true) do |form| %>

  <%-# The part variable: to know if this is a new or an existing constraint which is modified (see below) -%>
  <% part = request.path_info.split("/")[4] %>
  <%-# Add a title according if this is a new or an existing constraint -%>
  <% if part == 'edit' %>
    <%-# This is an existing constraint. -%>
    <h2>Contrainte "<%= constraint.title %>"</h2>
    Tâche : <%= constraint.task.title %> (Action : <%= constraint.task.action.code %> <%= constraint.task.action.title %> - Thème : <%= constraint.task.action.theme.code %> <%= constraint.task.action.theme.title %>)
    <%-# No <h2> title if this is a new constraint. -%>
  <% end %>

  <% if constraint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(constraint.errors.count, "erreur identifiée", "erreurs identifiées") %> :</h2>

      <ul>
      <% constraint.errors.messages.values.each do |message| %>
        <li><%= message[0] %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <hr/><h3>Information sur la contrainte</h3><br/>

  <div class="field">
    Titre de la contrainte* : <br/>
    <%= form.autocomplete_field :title, autocomplete_constraint_title_constraints_path, id: :constraint_title, size: '43.5' %>
  </div>

  <div class="field">
    Description de la contrainte : <br/>
    <%= form.text_area :description, id: :constraint_description, size: '40x5' %>
  </div>

  <div class="field">
    Tâche (Action - Thème)* : <br/>
    <%= form.select :task_id, Task.all.collect { |task| [task.title + ' (' + task.action.code + ' ' + task.action.title + ' - ' + task.action.theme.code + ' ' + task.action.theme.title + ')', task.id] }, { :include_blank => "Choisir" } %>
    <%= link_to 'Créer une nouvelle tâche', new_task_path %>
  </div>

  <hr/>
  <h6>* Champs obligatoires</h6>
  <div class="actions">
    <%= form.submit 'Enregistrer' %>
  </div>
<% end %>

app/views/constraints/edit.html.erb
<h1>Modification d'une contrainte</h1>

<%= render 'form', constraint: @constraint %>

<%= link_to 'Annuler', constraints_path %>

app/views/constraints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Table des contraintes</h1>
<em>
  Cette table contient les différentes contraintes des tâches.
</em>

<hr/>
<%= link_to 'Ajouter une contrainte', new_constraint_path %>
<hr/>

<h3>Effectuer une recherche</h3><br/>
<%= form_tag(constraints_path, method: :get) do %>

  <div class="field">
    Mot-clé cherché dans le titre et la description :
    <%= text_field_tag :keyword, params[:keyword], size: '30', placeholder: 'Aucun mot-clé' %>
  </div>
  
  <div class="field">
    Tâche (Action - Thème) :
    <% tasks = Task.all %>
    <% taskoptions = ['Indifférent'] %>
    <% tasks.each do |task| %>
      <% taskarray = [task.title + ' (' + task.action.code + ' ' + task.action.title + ' - ' + task.action.theme.code + ' ' + task.action.theme.title + ')', task.id] %>
      <% taskoptions.push(taskarray) %>
    <% end %>
    <%= select_tag :task_id, options_for_select(taskoptions, params[:task_id]) %>
  </div>

  <div class="actions">
    <%= submit_tag 'Rechercher', name: nil %>
  </div>

<% end %><br/>

<%= link_to 'Annuler la recherche', constraints_path %><br/><br/>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Titre de la contrainte</th>
      <th>Description de la contrainte</th>
      <th>Tâche (Action - Thème)</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @constraints.each do |constraint| %>
      <tr>
        <td><%= constraint.title %></td>
        <td><%= simple_format(markdown(constraint.description)) %></td>
        <td><%= constraint.task.title %> (<%= constraint.task.action.code %> <%= constraint.task.action.title %> - <%= constraint.task.action.theme.code %> <%= constraint.task.action.theme.title %>)</td>
        <td>
          <%= link_to 'Editer', edit_constraint_path(constraint) %><br/>
          <%= link_to 'Supprimer', constraint, method: :delete, data: { confirm: 'Etes-vous sûr ? Attention : La suppression de cette contrainte est irréversible.' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/constraints/new.html.erb
<h1>Ajout d'une nouvelle contrainte (pour les tâches)</h1>

<%= render 'form', constraint: @constraint %>

<%= link_to 'Annuler', constraints_path %>

app/views/constraints/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Contrainte "<%= @constraint.title %>"</h1>

<hr/>
<%= link_to 'Voir toutes les contraintes', constraints_path %>
<hr/>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Titre de la contrainte</th>
      <th>Description de la contrainte</th>
      <th>Tâche (Action - Thème)</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @constraint.title %></td>
      <td><%= @constraint.description %></td>
      <td><%= @constraint.task.title %> (<%= @constraint.task.action.code %> <%= @constraint.task.action.title %> - <%= @constraint.task.action.theme.code %> <%= @constraint.task.action.theme.title %>)</td>
      <td>
        <%= link_to 'Editer', edit_constraint_path(@constraint) %><br/>
        <%= link_to 'Supprimer', @constraint, method: :delete, data: { confirm: 'Etes-vous sûr ? Attention : La suppression de cette contrainte est irréversible.' } %>
      </td>
    </tr>
  </tbody>
</table>