config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/tables')

  resource :session, only: [:new, :create, :destroy]
  get '/tables', to: 'tables#index'

  resources :actions, path: '/tables/actions' do
    get :autocomplete_action_title, :on => :collection
    get :autocomplete_action_code, :on => :collection
  end

  resources :types, path: '/tables/types' do
    get :autocomplete_type_title, :on => :collection
  end

  resources :themes, path: '/tables/themes' do
    get :autocomplete_theme_title, :on => :collection
    get :autocomplete_theme_code, :on => :collection
  end

  resources :costs, path: '/tables/costs' do
    get :autocomplete_cost_title, :on => :collection
    get :autocomplete_cost_unit, :on => :collection
  end

  resources :species, path: '/tables/species' do
    get :autocomplete_species_common_name, :on => :collection
    get :autocomplete_species_latin_name, :on => :collection
  end

  resources :tasks, path: '/tables/tasks' do
    get :autocomplete_task_title, :on => :collection
    get :autocomplete_task_code, :on => :collection
  end

  resources :constraints, path: '/tables/constraints' do
    get :autocomplete_constraint_title, :on => :collection
  end

  resources :links, path: '/tables/links' do
    get :autocomplete_link_link, :on => :collection
  end

  resources :categories, path: '/tables/categories' do
    get :autocomplete_category_title, :on => :collection
  end

  resources :units, path: '/tables/units' do
    get :autocomplete_unit_abbreviation, :on => :collection
    get :autocomplete_unit_name, :on => :collection
  end

  resources :periods, path: '/tables/periods'
  resources :actions_actions, path: '/tables/actionsActions'
  resources :tasks_tasks, path: '/tables/tasksTasks'
  resources :species_actions, path: '/tables/speciesActions'

  # Default route (if unknown url)
  match '*path' => redirect('/tables'), via: [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :action, optional: true

  has_many :links, dependent: :destroy
  has_many :constraints, dependent: :destroy
  has_many :pictures, dependent: :destroy
  has_many :periods, dependent: :destroy
  has_many :ref_tasks, foreign_key: :ref_id, class_name: :TasksTask, dependent: :destroy
  has_many :dep_tasks, foreign_key: :dep_id, class_name: :TasksTask, dependent: :destroy

  before_validation :strip_blanks

  validates_presence_of :title, :message => 'Le titre de la tâche doit être spécifié.'
  validates_uniqueness_of :title, :case_sensitive => false, :message => 'Le titre de la tâche est déjà utilisé.'
  validates_length_of :title, :maximum => 100, :message => 'Le titre de la tâche doit avoir maximum 100 caractères.'
  validates_length_of :code, :maximum => 10, :message => 'Le code de la tâche doit avoir maximum 10 caractères.'
  validates_presence_of :description, :message => 'La description complète de la tâche doit être spécifiée.'
  validates_length_of :time, :maximum => 1500, :message => 'Le temps de la tâche doit avoir maximum 1500 caractères.'
  validates_length_of :recommendation, :maximum => 1500, :message => 'L\'information / recommandation de la tâche doit avoir maximum 1500 caractères.'
  validates_length_of :complement_title, :maximum => 30, :message => 'Le titre de l\'encart curiosité de la tâche doit avoir maximum 30 caractères.'
  validates_numericality_of :action_id, :greater_than_or_equal_to => 0, :message => 'Choisir une action pour cette tâche.'

  # Function to remove spaces in the fields
  def strip_blanks
    self.title = self.title.strip
    self.code = self.code.strip
    self.complement_title = self.complement_title.strip
  end

  # Function search to search a keyword through a form
  def self.search(keyword, action)

    if action != "Indifférent"
      sql_action = "action_id = #{action.to_f}"
    else
      sql_action = ""
    end

    if keyword && sql_action == ""
      where("title iLIKE :term OR code iLIKE :term OR description iLIKE :term OR time iLIKE :term OR recommendation iLIKE :term OR complement_title iLIKE :term OR complement_description iLIKE :term", term: "%#{keyword}%").order(updated_at: :desc)
      # iLIKE -> case insensitive
    elsif keyword && sql_action != ""
      where(sql_action + " AND (title iLIKE :term OR code iLIKE :term OR description iLIKE :term OR time iLIKE :term OR recommendation iLIKE :term OR complement_title iLIKE :term OR complement_description iLIKE :term)", term: "%#{keyword}%").order(updated_at: :desc)
    else
      all.order(updated_at: :desc)
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < AuthenticateController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  autocomplete :task, :title, :full => true
  autocomplete :task, :code, :full => true

  # GET /tasks
  # GET /tasks.json
  def index
    keyword = params[:keyword]
    action = params[:action_id]
    @tasks = Task.search(keyword, action)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'La tâche a été créée.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'La tâche a été mise à jour.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'La tâche a été supprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :code, :description, :time, :recommendation, :complement_title, :complement_description, :action_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>

  <%-# The part variable: to know if this is a new or an existing task which is modified (see below) -%>
  <% part = request.path_info.split("/")[4] %>
  <%-# Add a title according if this is a new or an existing task -%>
  <% if part == 'edit' %>
    <%-# This is an existing task. -%>
    <h2>Tâche "<%= task.title %>"</h2>
    Action : <%= task.action.code %> <%= task.action.title %> (Thème : <%= task.action.theme.code %> <%= task.action.theme.title %>)
    <%-# No <h2> title if this is a new task. -%>
  <% end %>

  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "erreur identifiée", "erreurs identifiées") %> :</h2>

      <ul>
      <% task.errors.messages.values.each do |message| %>
        <li><%= message[0] %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <hr/><h3>Information sur la tâche</h3><br/>

  <div class="field">
    Titre de la tâche* : <br/>
    <%= form.autocomplete_field :title, autocomplete_task_title_tasks_path, id: :task_title, size: '43.5' %>
  </div>

  <div class="field">
    Code de la tâche : <br/>
    <%= form.autocomplete_field :code, autocomplete_task_code_tasks_path, id: :task_code, size: '10' %>
  </div>

  <div class="field">
    Description complète de la tâche* : <br/>
    <%= form.text_area :description, id: :task_description, size: '40x5' %>
  </div>

  <div class="field">
    Temps de la tâche : <br/>
    <%= form.text_area :time, id: :task_time, size: '40x5' %>
  </div>

  <div class="field">
    Information / recommandation de la tâche : <br/>
    <%= form.text_area :recommendation, id: :task_recommendation, size: '40x5' %>
  </div>

  <hr/><h3>Encart curiosité de la tâche</h3><br/>

  <div class="field">
    Titre de l'encart curiosité de la tâche : <br/>
    <%= form.text_field :complement_title, id: :task_complement_title, size: '43.5' %>
  </div>

  <div class="field">
    Description de l'encart curiosité de la tâche : <br/>
    <%= form.text_area :complement_description, id: :task_complement_description, size: '40x5' %>
  </div>

  <hr/><h3>Classification de la tâche</h3><br/>

  <div class="field">
    Action (Thème)* : <br/>
    <%= form.select :action_id, Action.all.collect { |action| [action.code + ' ' + action.title + ' (' + action.theme.code + ' ' + action.theme.title + ')', action.id] }, { :include_blank => "Choisir" } %>
    <%= link_to 'Créer une nouvelle action', new_action_path %>
  </div>

  <hr/>
  <h6>* Champs obligatoires</h6>
  <div class="actions">
    <%= form.submit 'Enregistrer' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Modification d'une tâche</h1>

<%= render 'form', task: @task %>

<%= link_to 'Annuler', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Table des tâches</h1>
<em>
  Cette table contient les différentes tâches de chacune des actions.<br/>
  Une tâche par ligne. Une action (table "Actions") peut avoir plusieurs tâches. En revanche, une tâche n'appartient qu'à une seule action.
</em>

<hr/>
<%# Button to add a new task: at the top %>
<%= link_to 'Ajouter une nouvelle tâche', new_task_path %>
<hr/>

<h3>Effectuer une recherche</h3><br/>
<%= form_tag(tasks_path, method: :get) do %>

  <div class="field">
    Mot-clé cherché dans le titre, le code, le temps, les informations / recommandations et le titre et la description de l'encart curiosité :
    <%= text_field_tag :keyword, params[:keyword], size: '30', placeholder: 'Aucun mot-clé' %>
  </div>

  <div class="field">
    Action (Thème) :
    <% actions = Action.all %>
    <% actionoptions = ['Indifférent'] %>
    <% actions.each do |action| %>
      <% actionarray = [action.code + ' ' + action.title + ' (' + action.theme.code + ' ' + action.theme.title + ')', action.id] %>
      <% actionoptions.push(actionarray) %>
    <% end %>
    <%= select_tag :action_id, options_for_select(actionoptions, params[:action_id]) %>
  </div>

  <div class="actions">
    <%= submit_tag 'Rechercher', name: nil %>
  </div>

<% end %><br/>

<%= link_to 'Annuler la recherche', tasks_path %><br/><br/>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Titre de la tâche</th>
      <th>Code de la tâche</th>
      <th>Action (Thème)</th>
      <th>Description complète de la tâche</th>
      <th>Temps</th>
      <th>Contraintes de la tâche</th>
      <th>Information / recommandation</th>
      <th>Titre de l'encart curiosité</th>
      <th>Description de l'encart curiosité</th>
      <th>Tâches liées à la présente tâche</th>
      <th>Liens Internet relatifs à la tâche</th>
      <th>Périodes relatives à la tâche</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.code %></td>
        <td><%= task.action.code %> <%= task.action.title %> (<%= task.action.theme.code %> <%= task.action.theme.title %>)</td>
        <td><%= simple_format(markdown(task.description)) %></td>
        <td><%= simple_format(markdown(task.time)) %></td>
        <td>
          <% if Constraint.where(["task_id = ?", task.id]).count > 0 %>
            <%= link_to 'Voir les différentes contraintes relatives à cette tâche', constraints_url + '?utf8=✓&keyword=&task_id=' + task.id.to_s, class: 'with-features' %>
          <% else %>
            <%= link_to 'Il n\'y a aucune contrainte relative à cette tâche.', constraints_url + '?utf8=✓&keyword=&task_id=' + task.id.to_s, class: 'no-feature' %>
          <% end %>
        </td>
        <td><%= simple_format(markdown(task.recommendation)) %></td>
        <td><%= task.complement_title %></td>
        <td><%= simple_format(markdown(task.complement_description)) %></td>
        <td>
          <% if TasksTask.where(["ref_id = ? OR dep_id = ?", task.id, task.id]).count > 0 %>
            <%= link_to 'Voir les différentes tâches liées à cette tâche', tasks_tasks_url + '?utf8=✓&task_id=' + task.id.to_s, class: 'with-features' %>
          <% else %>
            <%= link_to 'Il n\'y a aucune autre tâche liée à cette tâche.', tasks_tasks_url + '?utf8=✓&task_id=' + task.id.to_s, class: 'no-feature' %>
          <% end %>
        </td>
        <td>
          <% if Link.where(["task_id = ?", task.id]).count > 0 %>
            <%= link_to 'Voir les différents liens Internet relatifs à cette tâche', links_url + '?utf8=✓&keyword=&task_id=' + task.id.to_s, class: 'with-features' %>
          <% else %>
            <%= link_to 'Il n\'y a aucun lien Internet relatif à cette tâche.', links_url + '?utf8=✓&keyword=&task_id=' + task.id.to_s, class: 'no-feature' %>
          <% end %>
        </td>
        <td>
          <% if Period.where(["task_id = ?", task.id]).count > 0 %>
            <%= link_to 'Voir les différentes périodes relatives à cette tâche', periods_url + '?utf8=✓&keyword=&monthmin=0&monthmax=0&category_id=Indifférent&task_id=' + task.id.to_s, class: 'with-features' %>
          <% else %>
            <%= link_to 'Il n\'y aucune période relative à cette tâche.', periods_url + '?utf8=✓&keyword=&monthmin=0&monthmax=0&category_id=Indifférent&task_id=' + task.id.to_s, class: 'no-feature' %>
          <% end %>
        </td>
        <td>
          <%= link_to 'Editer', edit_task_path(task) %><br/>
          <%= link_to 'Supprimer', task, method: :delete, data: { confirm: 'Etes-vous sûr ? Attention : La suppression de cette tâche est irréversible et supprimera toutes les lignes associées dans les tables "Liens", "Contraintes" et "Périodes".' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<h1>Ajout d'une nouvelle tâche</h1>

<%= render 'form', task: @task %>

<%= link_to 'Annuler', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Tâche "<%= @task.title %>"</h1>

<hr/>
<%= link_to 'Voir toutes les tâches', tasks_path %>
<hr/>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Titre de la tâche</th>
      <th>Code de la tâche</th>
      <th>Action (Thème)</th>
      <th>Description complète de la tâche</th>
      <th>Temps</th>
      <th>Contraintes de la tâche</th>
      <th>Information / recommandation</th>
      <th>Titre de l'encart curiosité</th>
      <th>Description de l'encart curiosité</th>
      <th>Tâches liées à la présente tâche</th>
      <th>Liens Internet relatifs à la tâche</th>
      <th>Périodes relatives à la tâche</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @task.title %></td>
      <td><%= @task.code %></td>
      <td><%= @task.action.code %> <%= @task.action.title %> (<%= @task.action.theme.code %> <%= @task.action.theme.title %>)</td>
      <td><%= simple_format(markdown(@task.description)) %></td>
      <td><%= simple_format(markdown(@task.time)) %></td>
      <td>
        <% if Constraint.where(["task_id = ?", @task.id]).count > 0 %>
          <%= link_to 'Voir les différentes contraintes relatives à cette tâche', constraints_url + '?utf8=✓&keyword=&task_id=' + @task.id.to_s, class: 'with-features' %>
        <% else %>
          <%= link_to 'Il n\'y a aucune contrainte relative à cette tâche.', constraints_url + '?utf8=✓&keyword=&task_id=' + @task.id.to_s, class: 'no-feature' %>
        <% end %>
      </td>
      <td><%= simple_format(markdown(@task.recommendation)) %></td>
      <td><%= @task.complement_title %></td>
      <td><%= simple_format(markdown(@task.complement_description)) %></td>
      <td>
        <% if TasksTask.where(["ref_id = ? OR dep_id = ?", @task.id, @task.id]).count > 0 %>
          <%= link_to 'Voir les différentes tâches liées à cette tâche', tasks_tasks_url + '?utf8=✓&task_id=' + @task.id.to_s, class: 'with-features' %>
        <% else %>
          <%= link_to 'Il n\'y a aucune autre tâche liée à cette tâche.', tasks_tasks_url + '?utf8=✓&task_id=' + @task.id.to_s, class: 'no-feature' %>
        <% end %>
      </td>
      <td>
        <% if Link.where(["task_id = ?", @task.id]).count > 0 %>
          <%= link_to 'Voir les différents liens Internet relatifs à cette tâche', links_url + '?utf8=✓&keyword=&task_id=' + @task.id.to_s, class: 'with-features' %>
        <% else %>
          <%= link_to 'Il n\'y a aucun lien Internet relatif à cette tâche.', links_url + '?utf8=✓&keyword=&task_id=' + @task.id.to_s, class: 'no-feature' %>
        <% end %>
      </td>
      <td>
        <% if Period.where(["task_id = ?", @task.id]).count > 0 %>
          <%= link_to 'Voir les différentes périodes relatives à cette tâche', periods_url + '?utf8=✓&keyword=&monthmin=0&monthmax=0&category_id=Indifférent&task_id=' + @task.id.to_s, class: 'with-features' %>
        <% else %>
          <%= link_to 'Il n\'y aucune période relative à cette tâche.', periods_url + '?utf8=✓&keyword=&monthmin=0&monthmax=0&category_id=Indifférent&task_id=' + @task.id.to_s, class: 'no-feature' %>
        <% end %>
      </td>
      <td>
        <%= link_to 'Editer', edit_task_path(@task) %><br/>
        <%= link_to 'Supprimer', @task, method: :delete, data: { confirm: 'Etes-vous sûr ? Attention : La suppression de cette tâche est irréversible et supprimera toutes les lignes associées dans les tables "Liens", "Contraintes" et "Périodes".' } %>
      </td>
    </tr>
  </tbody>
</table>