config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/tables')

  resource :session, only: [:new, :create, :destroy]
  get '/tables', to: 'tables#index'

  resources :actions, path: '/tables/actions' do
    get :autocomplete_action_title, :on => :collection
    get :autocomplete_action_code, :on => :collection
  end

  resources :types, path: '/tables/types' do
    get :autocomplete_type_title, :on => :collection
  end

  resources :themes, path: '/tables/themes' do
    get :autocomplete_theme_title, :on => :collection
    get :autocomplete_theme_code, :on => :collection
  end

  resources :costs, path: '/tables/costs' do
    get :autocomplete_cost_title, :on => :collection
    get :autocomplete_cost_unit, :on => :collection
  end

  resources :species, path: '/tables/species' do
    get :autocomplete_species_common_name, :on => :collection
    get :autocomplete_species_latin_name, :on => :collection
  end

  resources :tasks, path: '/tables/tasks' do
    get :autocomplete_task_title, :on => :collection
    get :autocomplete_task_code, :on => :collection
  end

  resources :constraints, path: '/tables/constraints' do
    get :autocomplete_constraint_title, :on => :collection
  end

  resources :links, path: '/tables/links' do
    get :autocomplete_link_link, :on => :collection
  end

  resources :categories, path: '/tables/categories' do
    get :autocomplete_category_title, :on => :collection
  end

  resources :units, path: '/tables/units' do
    get :autocomplete_unit_abbreviation, :on => :collection
    get :autocomplete_unit_name, :on => :collection
  end

  resources :periods, path: '/tables/periods'
  resources :actions_actions, path: '/tables/actionsActions'
  resources :tasks_tasks, path: '/tables/tasksTasks'
  resources :species_actions, path: '/tables/speciesActions'

  # Default route (if unknown url)
  match '*path' => redirect('/tables'), via: [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cost.rb
class Cost < ApplicationRecord
  belongs_to :action, optional: true

  before_validation :strip_blanks

  validates_presence_of :title, :message => 'Le titre du coût de l\'action doit être spécifié.'
  validates_length_of :title, :maximum => 40, :message => 'Le titre du coût de l\'action doit avoir maximum 40 caractères.'
  validates_presence_of :value_min, :message => 'La valeur minimale du coût de l\'action doit être spécifiée.'
  validates_numericality_of :value_min, :allow_nil => true, :greater_than_or_equal_to => 0, :message => 'La valeur minimale du coût de l\'action doit être nulle ou définie par un nombre positif.'
  validates_presence_of :value_max, :message => 'La valeur maximale du coût de l\'action doit être spécifiée.'
  validates_numericality_of :value_max, :allow_nil => true, :greater_than_or_equal_to => 0, :message => 'La valeur maximale du coût de l\'action doit être nulle ou définie par un nombre positif.'
  validates_presence_of :unit, :message => 'L\'unité du coût de l\'action doit être spécifié.'
  validates_length_of :unit, :maximum => 20, :message => 'L\'unité du coût de l\'action doit avoir maximum 40 caractères.'
  validates_numericality_of :action_id, :greater_than_or_equal_to => 0, :message => 'Choisir une action pour ce coût.'
  
  # Function to remove spaces in the title and unit fields
  def strip_blanks
    self.title = self.title.strip
    self.unit = self.unit.strip
  end
  
  # Function search to search a keyword through a form
  def self.search(keyword, costmin, costmax, action)

    # The minimum cost equals 0.0.
    if costmax != ""
      sql_cost = "value_min >= #{costmin.to_f} AND value_max <= #{costmax.to_f}"
    else
      sql_cost = "value_min >= #{costmin.to_f}"
    end

    if action != "Indifférent"
      sql_action = "action_id = #{action.to_f}"
    else
      sql_action = ""
    end

    if keyword && sql_action == ""
      where(sql_cost + " AND (title iLIKE :term OR unit iLIKE :term)", term: "%#{keyword}%").order(updated_at: :desc)
      # iLIKE -> case insensitive
    elsif keyword && sql_action != ""
      where(sql_cost + " AND " + sql_action + " AND (title iLIKE :term OR unit iLIKE :term)", term: "%#{keyword}%").order(updated_at: :desc)
    else
      all.order(updated_at: :desc)
    end
  end
end

app/controllers/costs_controller.rb
class CostsController < AuthenticateController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]
  autocomplete :cost, :title, :full => true
  autocomplete :cost, :unit, :full => true

  # GET /costs
  # GET /costs.json
  def index
    keyword = params[:keyword]
    costmin = params[:costmin]
    costmax = params[:costmax]
    action = params[:action_id]
    @costs = Cost.search(keyword, costmin, costmax, action)
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @cost, notice: 'Le coût a été créé.' }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Le coût a été mis à jour.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Le coût a été supprimé.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:title, :value_min, :value_max, :unit, :action_id)
    end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<%= form_with(model: cost, local: true) do |form| %>

  <%-# The part variable: to know if this is a new or an existing cost which is modified (see below) -%>
  <% part = request.path_info.split("/")[4] %>
  <%-# Add a title according if this is a new or an existing cost -%>
  <% if part == 'edit' %>
    <%-# This is an existing cost. -%>
    <h2>Coût "<%= cost.title %>"</h2>
    Action : <%= @cost.action.code %> <%= @cost.action.title %> (Thème : <%= @cost.action.theme.title %> - Code du thème : <%= @cost.action.theme.code %>)
    <%-# No <h2> title if this is a new cost. -%>
  <% end %>

  <% if cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cost.errors.count, "erreur identifiée", "erreurs identifiées") %> :</h2>

      <ul>
      <% cost.errors.messages.values.each do |message| %>
        <li><%= message[0] %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <hr/><h3>Information sur le coût</h3><br/>

  <div class="field">
    Titre* : <br/>
    <%= form.autocomplete_field :title, autocomplete_cost_title_costs_path, id: :cost_title, size: '43.5' %>
  </div>

  <div class="field">
    Coût minimum* : <br/>
    <%= form.text_field :value_min, id: :cost_value_min, size: '43.5' %>
  </div>

  <div class="field">
    Coût maximum* : <br/>
    <%= form.text_field :value_max, id: :cost_value_max, size: '43.5' %>
  </div>

  <div class="field">
    Unité (pour les coûts)* : <br/>
    <%= form.autocomplete_field :unit, autocomplete_cost_unit_costs_path, id: :cost_unit, size: '43.5' %>
  </div>

  <hr/><h3>Classification du coût</h3><br/>

  <div class="field">
    Action (Thème - Code du thème)* : <br/>
    <%= form.select :action_id, Action.all.collect { |action| [action.code + ' ' + action.title + ' (' + action.theme.title + ' - ' + action.theme.code + ')', action.id] }, { :include_blank => "Choisir" } %>
    <%= link_to 'Créer une nouvelle action', new_action_path %>
  </div>
  
  <hr/>
  <h6>* Champs obligatoires</h6>
  <div class="actions">
    <%= form.submit 'Enregistrer' %>
  </div>
<% end %>

app/views/costs/edit.html.erb
<h1>Modification d'un coût</h1>

<%= render 'form', cost: @cost %>

<%= link_to 'Annuler', costs_path %>

app/views/costs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Table des coûts (pour les actions)</h1>
<em>
  Cette table concerne les coûts des actions.<br/>
  Une action (table "Actions") peut être composée de différents coûts. Par contre, une ligne de cette table ne concerne qu'une seule action (pas plusieurs actions).
</em>

<hr/>
<%-# Button to add a new cost: at the top -%>
<%= link_to 'Ajouter un nouveau coût', new_cost_path %>
<hr/>

<h3>Effectuer une recherche</h3><br/>
<%= form_tag(costs_path, method: :get) do %>

  <div class="field">
    Mot-clé cherché dans le titre et l'unité (pour les coûts) :
    <%= text_field_tag :keyword, params[:keyword], size: '30', placeholder: 'Aucun mot-clé' %>
  </div>

  <div class="field">
    Coût minimum :
    <%= number_field_tag :costmin, params[:costmin], step: 0.1, min: 0, max: 500, placeholder: 'Aucun' %>
  </div>

  <div class="field">
    Coût maximum :
    <%= number_field_tag :costmax, params[:costmax], step: 0.1, min: 0, max: 500, placeholder: 'Aucun' %>
  </div>

  <div class="field">
    Action (Thème - Code du thème) :
    <% actions = Action.all %>
    <% actionoptions = ['Indifférent'] %>
    <% actions.each do |action| %>
      <% actionarray = [action.code + ' ' + action.title + ' (' + action.theme.title + ' - ' + action.theme.code + ')', action.id] %>
      <% actionoptions.push(actionarray) %>
    <% end %>
    <%= select_tag :action_id, options_for_select(actionoptions, params[:action_id]) %>
  </div>

  <div class="actions">
    <%= submit_tag 'Rechercher', name: nil %>
  </div>

<% end %><br/>

<%= link_to 'Annuler la recherche', costs_path %><br/><br/>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Titre / type de coût</th>
      <th>Action (Thème - Code du thème)</th>
      <th>Coût minimum</th>
      <th>Coût maximum</th>
      <th>Unité (pour les coûts)</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= cost.title %></td>
        <td><%= cost.action.code %> <%= cost.action.title %> (<%= cost.action.theme.title %> - <%= cost.action.theme.code %>)</td>
        <td><%= cost.value_min %></td>
        <td><%= cost.value_max %></td>
        <td><%= cost.unit %></td>
        <td>
          <%= link_to 'Editer', edit_cost_path(cost) %><br/>
          <%= link_to 'Supprimer', cost, method: :delete, data: { confirm: 'Etes-vous sûr ? Attention : La suppression de ce coût est irréversible.' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/costs/new.html.erb
<h1>Ajout d'un nouveau coût (pour les actions)</h1>

<%= render 'form', cost: @cost %>

<%= link_to 'Annuler', costs_path %>

app/views/costs/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Coût "<%= @cost.title %>"</h1>

<hr/>
<%= link_to 'Voir tous les coûts', costs_path %>
<hr/>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Titre / type de coût</th>
      <th>Action (Thème - Code du thème)</th>
      <th>Coût minimum</th>
      <th>Coût maximum</th>
      <th>Unité (pour les coûts)</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @cost.title %></td>
      <td><%= @cost.action.code %> <%= @cost.action.title %> (<%= @cost.action.theme.title %> - <%= @cost.action.theme.code %>)</td>
      <td><%= @cost.value_min %></td>
      <td><%= @cost.value_max %></td>
      <td><%= @cost.unit %></td>
      <td>
        <%= link_to 'Editer', edit_cost_path(@cost) %><br/>
        <%= link_to 'Supprimer', @cost, method: :delete, data: { confirm: 'Etes-vous sûr ? Attention : La suppression de ce coût est irréversible.' } %>
      </td>
    </tr>
  </tbody>
</table>