config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/tables')

  resource :session, only: [:new, :create, :destroy]
  get '/tables', to: 'tables#index'

  resources :actions, path: '/tables/actions' do
    get :autocomplete_action_title, :on => :collection
    get :autocomplete_action_code, :on => :collection
  end

  resources :types, path: '/tables/types' do
    get :autocomplete_type_title, :on => :collection
  end

  resources :themes, path: '/tables/themes' do
    get :autocomplete_theme_title, :on => :collection
    get :autocomplete_theme_code, :on => :collection
  end

  resources :costs, path: '/tables/costs' do
    get :autocomplete_cost_title, :on => :collection
    get :autocomplete_cost_unit, :on => :collection
  end

  resources :species, path: '/tables/species' do
    get :autocomplete_species_common_name, :on => :collection
    get :autocomplete_species_latin_name, :on => :collection
  end

  resources :tasks, path: '/tables/tasks' do
    get :autocomplete_task_title, :on => :collection
    get :autocomplete_task_code, :on => :collection
  end

  resources :constraints, path: '/tables/constraints' do
    get :autocomplete_constraint_title, :on => :collection
  end

  resources :links, path: '/tables/links' do
    get :autocomplete_link_link, :on => :collection
  end

  resources :categories, path: '/tables/categories' do
    get :autocomplete_category_title, :on => :collection
  end

  resources :units, path: '/tables/units' do
    get :autocomplete_unit_abbreviation, :on => :collection
    get :autocomplete_unit_name, :on => :collection
  end

  resources :periods, path: '/tables/periods'
  resources :actions_actions, path: '/tables/actionsActions'
  resources :tasks_tasks, path: '/tables/tasksTasks'
  resources :species_actions, path: '/tables/speciesActions'

  # Default route (if unknown url)
  match '*path' => redirect('/tables'), via: [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :actions, dependent: :destroy

  before_validation :strip_blanks

  validates_presence_of :abbreviation, :message => 'L\'abréviation de l\'unité de temps doit être spécifiée.'
  validates_length_of :abbreviation, :maximum => 40, :message => 'L\'abréviation de l\'unité de temps doit avoir maximum 40 caractères.'
  validates_uniqueness_of :abbreviation, :case_sensitive => false, :message => 'L\'abréviation de l\'unité de temps est déjà utilisé.'
  validates_length_of :name, :maximum => 40, :message => 'Le nom de l\'unité de temps doit avoir maximum 40 caractères.'

  def strip_blanks
    self.abbreviation = self.abbreviation.strip
    self.name = self.name.strip
  end
end

app/controllers/units_controller.rb
class UnitsController < AuthenticateController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]
  autocomplete :unit, :abbreviation, :full => true
  autocomplete :unit, :name, :full => true

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'L\'unité de temps a été créée.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'L\'unité de temps a été mise à jour.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'L\'unité de temps a été supprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :abbreviation)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_with(model: unit, local: true) do |form| %>

  <%-# The part variable: to know if this is a new or an existing unit which is modified (see below) -%>
  <% part = request.path_info.split("/")[4] %>
  <%-# Add a title according if this is a new or an existing unit -%>
  <% if part == 'edit' %>
    <%-# This is an existing unit. -%>
    <h2>Unité de temps "<%= unit.abbreviation %>"</h2>
    <%-# No <h2> title if this is a new unit. -%>
  <% end %>

  <% if unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit.errors.count, "erreur identifiée", "erreurs identifiées") %> : </h2>

      <ul>
      <% unit.errors.messages.values.each do |message| %>
        <li><%= message[0] %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <hr/><h3>Information sur l'unité de temps</h3><br/>

  <div class="field">
    Abréviation de l'unité de temps* : <br/>
    <%= form.autocomplete_field :abbreviation, autocomplete_unit_abbreviation_units_path, id: :unit_abbreviation, size: '43.5' %>
  </div>

  <div class="field">
    Nom complet de l'unité de temps : <br/>
    <%= form.autocomplete_field :name, autocomplete_unit_name_units_path, id: :unit_name, size: '43.5' %>
  </div>

  <hr/>
  <h6>* Champ obligatoire</h6>
  <div class="actions">
    <%= form.submit 'Enregistrer' %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Modification d'une unité de temps</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Annuler', units_path %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Table des unités de temps (pour les actions)</h1>
<em>
  Cette table concerne les unités de temps des actions.
</em>

<hr/>
<%= link_to 'Ajouter une nouvelle unité de temps', new_unit_path %>
<hr/>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Abréviation de l'unité de temps</th>
      <th>Nom complet de l'unité de temps</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.abbreviation %></td>
        <td><%= unit.name %></td>
        <td>
          <%= link_to 'Editer', edit_unit_path(unit) %><br/>
          <%= link_to 'Supprimer', unit, method: :delete, data: { confirm: 'Etes-vous sûr ? Attention : La suppression de cette unité de temps est irréversible et suprimera toutes les actions associées.' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/units/new.html.erb
<h1>Ajout d'une nouvelle unité de temps (pour les actions)</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Annuler', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Abréviation de l'unité de temps : </strong>
  <%= @unit.abbreviation %>
</p>

<p>
  <strong>Nom de l'unité de temps : </strong>
  <%= @unit.name %>
</p>


<%= link_to 'Editer', edit_unit_path(@unit) %> |
<%= link_to 'Annuler', units_path %>